project:
  type: website
  output-dir: docs

website:
  favicon: images/favicon.png
  site-url: https://jacobknyspel.github.io/
  title: Jacob Knyspel
  search: true
  navbar:
    title: false
    logo: images/logo.png
    pinned: true
    right:
      - href: index.qmd
        text: Home
      - href: publications.qmd
        text: Publications
      - href: posts.qmd
        text: Posts
      - href: https://github.com/jacobknyspel
        icon: github
      - href: https://orcid.org/0000-0001-5600-4826
        text: "{{< ai orcid >}}"
      - href: mailto::jacob.knyspel@kcl.ac.uk
        text: "{{< fa envelope >}}"
  page-footer:
    background: light
    left:
      - "Copyright 2024, Jacob Knyspel"
    right:
      - href: https://github.com/jacobknyspel
        icon: github
      - href: https://orcid.org/0000-0001-5600-4826
        text: "{{< ai orcid >}}"
      - href: mailto::jacob.knyspel@kcl.ac.uk
        text: "{{< fa envelope >}}"

format:
  html:
    theme:
      - minty
      - styles.scss
    mainfont: Nunito
    css: styles.css
    toc: true
    page-layout: full
    # keywords: genetics, mental health, psychology
    pagetitle: "Jacob Knyspel"
    description-meta: "Jacob Knyspel"
    author-meta: "Jacob Knyspel"
    site-url: https://jacobknyspel.github.io/
