---
title: "Publications"
---

::: callout-note
## Last updated: 26/09/2026
:::

## 2026

<ul class="fa-ul">

  <li class="li-pad"><span class="fa-li"><i class="fa-solid fa-file-pen"></i></span>
    <u>**Knyspel, J.**</u>, Kakar, S., Carnegie, A., Kalsi, G., Meldrum. L., Smith, I., Bristow, S., Davies, M., Armour, C., Eley, T.C., Breen, G., Wong, C.C.Y., & Coleman, J.R.I. (2026). Identifying differential interactions of traumatic experiences with genetic risk for posttraumatic stress disorder. *European Journal of Psychotraumatology*, *17*(1), 2709319. <https://doi.org/10.1080/20008066.2026.2709319><br>
    <span class="badge bg-success">Open Access {{<ai open-access>}}</span>
    [<span class="badge bg-info bg-link">Download PDF {{<fa file-pdf>}}</span>](https://www.tandfonline.com/doi/pdf/10.1080/20008066.2026.2709319?download=true)
  </li>
  
</ul>

## 2025

<ul class="fa-ul">

  <li class="li-pad"><span class="fa-li"><i class="fa-solid fa-file-pen"></i></span>
    Procopio, F., Keser, E., <u>**Knyspel, J.**</u>, Malanchini, M., Rimfeld, K., Allegrini, A., & Plomin, R. (2025). The genetic specificity of specific cognitive abilities after controlling for general cognitive ability. *Behavior Genetics*, *55*, 103-113. <https://doi.org/10.1007/s10519-025-10213-5><br>
    <span class="badge bg-success">Open Access {{<ai open-access>}}</span>
    [<span class="badge bg-info bg-link">Download PDF {{<fa file-pdf>}}</span>](https://link.springer.com/content/pdf/10.1007/s10519-025-10213-5.pdf)
    [<span class="badge bg-info bg-link">View Preregistration {{<ai osf>}}</span>](https://osf.io/5qb4m)
  </li>
  
  <li class="li-pad"><span class="fa-li"><i class="fa-solid fa-file-pen"></i></span>
    <u>**Knyspel, J.**</u>, Morneau-Vaillancourt, G., & Eley, T. C. (2025). Using bifactor twin modeling to assess the genetic and environmental dimensionality of adult ADHD symptoms. *Behavior Genetics*, *55*, 1-11. <https://doi.org/10.1007/s10519-024-10204-y><br>
    <span class="badge bg-success">Open Access {{<ai open-access>}}</span>
    [<span class="badge bg-info bg-link">Download PDF {{<fa file-pdf>}}</span>](https://link.springer.com/content/pdf/10.1007/s10519-024-10204-y.pdf)
    [<span class="badge bg-info bg-link">View Preregistration {{<ai osf>}}</span>](https://osf.io/emx8y)
  </li>
  
</ul>

## 2024

<ul class="fa-ul">
  
  <li class="li-pad"><span class="fa-li"><i class="fa-solid fa-file-pen"></i></span>
    <u>**Knyspel, J.**</u> & Plomin, R. (2024). Comparing factor and network models of cognitive abilities using twin data. *Intelligence*, *104*, 101833. <https://doi.org/10.1016/j.intell.2024.101833><br>
    <span class="badge bg-success">Open Access {{<ai open-access>}}</span>
    [<span class="badge bg-info bg-link">Download PDF {{<fa file-pdf>}}</span>](https://www.sciencedirect.com/science/article/pii/S0160289624000278/pdfft?md5=4fce9f2261c54e23fad5b161a8d215c5&pid=1-s2.0-S0160289624000278-main.pdf)
    [<span class="badge bg-info bg-link">View Preregistration {{<ai osf>}}</span>](https://osf.io/a4ewp)
  </li>
    
  <li class="li-pad"><span class="fa-li"><i class="fa-solid fa-file-pen"></i></span>
    Stantić, M., <u>**Knyspel, J.**</u>, Gaches, A., Liu, Y., Bird, G., & Catmur, C. (2024). The Oxford Face Matching Test: Short-form alternative. *Quarterly Journal of Experimental Psychology*, *77*(4), 893-897. <https://doi.org/10.1177/17470218231182933><br>
    <span class="badge bg-success">Open Access {{<ai open-access>}}</span>
    [<span class="badge bg-info bg-link">Download PDF {{<fa file-pdf>}}</span>](https://journals.sagepub.com/doi/pdf/10.1177/17470218231182933?download=true)
  </li>
    
</ul>
